exclude: [
  'Gemfile',
  'Gemfile.lock',
  'license.md',
  'readme.md',
  'vendor'
  ]

gems:
  - jekyll-language-plugin
  - jekyll-sitemap

sass:
    style: compressed

languages: ['en', 'fr']
language_data: data.lang.%%

url: 'https://laruche.io'
